### ISSUE TITLE
React 0.14

### ISSUE THREAD

**Issue by jeron-diovis** [deepsweet/valya#7]
Hi. Could you please provide a build for React 0.14? Or migrate to it completely, if it's possible for you?

**Comment by isnifer** [comment]
@jeron-diovis Yes, of course. I did it in 0.2.1.
@deepsweet please, publish current version to npm

**Comment by deepsweet** [comment]
```
npm owner add isnifer 'valya'
+ isnifer (valya)
```

:wink:

**Comment by isnifer** [comment]
@deepsweet awesome!

**Comment by isnifer** [comment]
@jeron-diovis 0.2.1 already available on npm. Try it out.

**Comment by jeron-diovis** [comment]
Cool, thanks!
